// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgsYZfOLy44H9LpUAIWBBiopyo3V_IUVc',
    appId: '1:580792631892:ios:48987aeb2fd17432ef23c1',
    messagingSenderId: '580792631892',
    projectId: 'thrive360-a88e2',
    storageBucket: 'thrive360-a88e2.firebasestorage.app',
    iosClientId: '580792631892-vnbh7ntgjnj0og8n0fjdqfck516gbrf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCnqLv5SlBxl5qBPMMq_FYP4Ha4x4l9uU',
    appId: '1:580792631892:web:efa37a07e9a98280ef23c1',
    messagingSenderId: '580792631892',
    projectId: 'thrive360-a88e2',
    authDomain: 'thrive360-a88e2.firebaseapp.com',
    storageBucket: 'thrive360-a88e2.firebasestorage.app',
    measurementId: 'G-WR2G96VWGP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnqLv5SlBxl5qBPMMq_FYP4Ha4x4l9uU',
    appId: '1:580792631892:web:efa37a07e9a98280ef23c1',
    messagingSenderId: '580792631892',
    projectId: 'thrive360-a88e2',
    authDomain: 'thrive360-a88e2.firebaseapp.com',
    storageBucket: 'thrive360-a88e2.firebasestorage.app',
    measurementId: 'G-WR2G96VWGP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsYZfOLy44H9LpUAIWBBiopyo3V_IUVc',
    appId: '1:580792631892:ios:48987aeb2fd17432ef23c1',
    messagingSenderId: '580792631892',
    projectId: 'thrive360-a88e2',
    storageBucket: 'thrive360-a88e2.firebasestorage.app',
    iosClientId: '580792631892-vnbh7ntgjnj0og8n0fjdqfck516gbrf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1fWlRGTQCDyMc1ZH-2guj90-cnL6wlc',
    appId: '1:580792631892:android:d4e7bc57a1c507d4ef23c1',
    messagingSenderId: '580792631892',
    projectId: 'thrive360-a88e2',
    storageBucket: 'thrive360-a88e2.firebasestorage.app',
  );

}